#!/bin/sh
# Builds Boxcar.app and a disk image into build/, with the sing-box core
# linked in. Building runs nothing: the app starts the core only when the
# user starts it.
#
#	./build.sh               the app, for this Mac's architecture
#	./build.sh -skip-dmg     without the disk image
set -e
cd "$(dirname "$0")"
[ -d frontend/node_modules ] || (cd frontend && bun install)

# The sing-box module go.mod requires: its version, and the protocols of
# its release builds.
CORE_DIR=$(go list -m -f '{{.Dir}}' github.com/sagernet/sing-box)
VERSION=$(go list -m -f '{{.Version}}' github.com/sagernet/sing-box | sed 's/^v//')
cat > version_gen.go <<GO
// Code generated by build.sh. DO NOT EDIT.

package main

func init() { coreVersion = "$VERSION" }
GO

# Without the tags that need -ldflags=-checklinkname=0, which mygo build
# sets itself.
TAGS=$(tr -d '\n' < "$CORE_DIR/release/DEFAULT_BUILD_TAGS_OTHERS" | tr ',' '\n' | grep -v -e '^badlinkname$' -e '^tfogo_checklinkname0$' | paste -sd, -)

# The schema and the documentation of the fields, for the visual editor.
go run ./tools/configschema

echo "sing-box $VERSION"
echo "tags: $TAGS"
CGO_ENABLED=0 GOFLAGS="-tags=$TAGS" go tool mygo build "$@"
