// Code generated by `mygo generate`. DO NOT EDIT.

import { call, event } from "mygo-runtime";

// ---- Types ----

/** About describes the build. */
export interface About {
  app: string;
  version: string;
  go: string;
  platform: string;
  mygo: string;
  tags: string[];
  dataDir: string;
}

/**
 * Activity is network work of the core that is not a routed connection,
 * and so not in the connections: DNS queries, rule-set downloads, URL
 * tests, NTP, rejected and hijacked connections. sing-box tells of them
 * only in its log, which its platform writer receives at every level.
 */
export interface Activity {
  time: string;
  kind: ActivityKind;
  level: string;
  tag: string;
  message: string;
}

/** ActivityKind is what a network activity of the core itself is. */
export type ActivityKind = "dns" | "rule-set" | "urltest" | "ntp" | "route";

/** CheckResult is the outcome of checking a configuration. */
export interface CheckResult {
  ok: boolean;
  error?: string;
  warnings: Warning[];
}

/** Connection is a connection the core routed. */
export interface Connection {
  id: string;
  inbound: string;
  inboundType: string;
  network: string;
  ipVersion?: number;
  source: string;
  destination: string;
  domain: string;
  protocol?: string;
  user?: string;
  process?: string;
  processPath?: string;
  processId?: number;
  rule: string;
  outbound: string;
  outboundType: string;
  chain: string[];
  upload: number;
  download: number;
  createdAt: string;
  /** ClosedAt is when the connection closed; zero while open. */
  closedAt?: string;
}

/** GroupItem is an outbound of a group. */
export interface GroupItem {
  tag: string;
  type: string;
  /** in milliseconds, 0 when untested */
  delay: number;
  /** TestedAt is when the delay was measured. */
  testedAt?: string;
}

/**
 * ImportResult are the profiles an import made, and the files it could
 * not import.
 */
export interface ImportResult {
  names: string[];
  failed: string[];
}

/** LogLine is a line of the core's log. */
export interface LogLine {
  time: string;
  level: string;
  message: string;
}

/**
 * ModeState is the Clash mode of the core: Rule, Global, Direct, or the
 * modes the configuration's rules name.
 */
export interface ModeState {
  current: string;
  list: string[];
}

/** OutboundGroup is a group of outbounds, as a selector or a urltest. */
export interface OutboundGroup {
  tag: string;
  type: string;
  selected: string;
  selectable: boolean;
  items: GroupItem[];
}

/** Profile is a configuration file. */
export interface Profile {
  name: string;
  path: string;
  size: number;
  modified: string;
  /** Remote is where the profile comes from, for a subscription. */
  remote: Remote | null;
}

/** Profiles are the configuration files, and the one Start runs. */
export interface Profiles {
  active: string;
  items: Profile[];
}

/** Remote is where a profile comes from when it is a subscription. */
export interface Remote {
  url: string;
  autoUpdate: boolean;
  /** Interval is the minutes between automatic updates, at least 15. */
  interval: number;
  updatedAt?: string;
  /** Error is why the last update failed, empty after a success. */
  error?: string;
}

/** RuleInfo is a rule of the router. */
export interface RuleInfo {
  index: number;
  type: string;
  rule: string;
  action: string;
}

/** Snapshot is the state of the core, sent to the page as it changes. */
export interface Snapshot {
  status: Status;
  profile: string;
  /**
   * StartedAt is when the core started, in Unix milliseconds; 0 while
   * stopped.
   */
  startedAt: number;
  /** Error is why the last start failed. */
  error?: string;
  stats: Stats;
  line: Station[];
  mode: ModeState;
  /** Warnings are the deprecated parts of the configuration running. */
  warnings: Warning[];
  /** LogLevel is the level the configuration running logs at. */
  logLevel?: string;
  systemProxy: SystemProxyState;
}

/** Station is a stop on the way traffic takes through the core. */
export interface Station {
  kind: StationKind;
  /** Title is the tag, or what the station is. */
  title: string;
  /** Detail is a short fact: an address, a type. */
  detail?: string;
}

/** StationKind is what a station of the line stands for. */
export type StationKind = "device" | "inbound" | "group" | "node" | "internet";

/** Stats are the figures of a running instance. */
export interface Stats {
  /** bytes in total */
  upload: number;
  /** bytes in total */
  download: number;
  /** bytes per second */
  uploadRate: number;
  /** bytes per second */
  downloadRate: number;
  /** Connections are the routed connections open. */
  connections: number;
  /** OutboundConnections are the connections the core holds to outbounds. */
  outboundConnections: number;
  memory: number;
  goroutines: number;
  /** the rates of the last minute */
  uploadHistory: number[];
  downHistory: number[];
}

/** Status is where the core is in its life. */
export type Status = "stopped" | "starting" | "running" | "stopping";

/** SystemProxyState is whether the system proxy points at sing-box. */
export interface SystemProxyState {
  /** Enabled is the setting: set it while sing-box runs. */
  enabled: boolean;
  /** Active is whether the app has set it now, and Address where to. */
  active: boolean;
  address?: string;
  /** Error is why setting it failed. */
  error?: string;
}

/** Theme is the appearance of the window. */
export type Theme = "system" | "light" | "dark";

/** Warning is a deprecated part of a configuration, as sing-box reports it. */
export interface Warning {
  message: string;
  link?: string;
  impending: boolean;
}

// ---- Services ----

/**
 * Box is the service the page calls: the embedded sing-box and the
 * profiles it runs.
 */
export const Box = {
  /** About describes the build. */
  about(): Promise<About> {
    return call("Box.About");
  },
  /**
   * Activity returns the core's own network work that is not a routed
   * connection, of a kind ("" for all), oldest first.
   */
  activity(kind: ActivityKind, query: string): Promise<Activity[]> {
    return call("Box.Activity", kind, query);
  },
  /**
   * AddRemoteProfile downloads a subscription and keeps it as a profile,
   * updated every interval minutes while autoUpdate.
   */
  addRemoteProfile(name: string, link: string, autoUpdate: boolean, interval: number): Promise<string> {
    return call("Box.AddRemoteProfile", name, link, autoUpdate, interval);
  },
  /**
   * CheckProfile checks a configuration as `sing-box check` does: it builds
   * an instance and closes it without starting it.
   */
  checkProfile(content: string): Promise<CheckResult> {
    return call("Box.CheckProfile", content);
  },
  /** ClearActivity empties the activity. */
  clearActivity(): Promise<void> {
    return call("Box.ClearActivity");
  },
  /** ClearClosedConnections forgets the connections closed. */
  clearClosedConnections(): Promise<void> {
    return call("Box.ClearClosedConnections");
  },
  /** ClearDNSCache empties the DNS cache of the running core. */
  clearDNSCache(): Promise<void> {
    return call("Box.ClearDNSCache");
  },
  /** ClearLogs empties the log. */
  clearLogs(): Promise<void> {
    return call("Box.ClearLogs");
  },
  /** CloseAllConnections closes every connection. */
  closeAllConnections(): Promise<void> {
    return call("Box.CloseAllConnections");
  },
  /** CloseConnection closes a connection. */
  closeConnection(id: string): Promise<void> {
    return call("Box.CloseConnection", id);
  },
  /**
   * Connections returns the connections the core routed, newest first:
   * those open, or those closed.
   */
  connections(closed: boolean): Promise<Connection[]> {
    return call("Box.Connections", closed);
  },
  /**
   * CurrentSystemProxy describes the system's HTTP proxy now, as set by
   * whichever app.
   */
  currentSystemProxy(): Promise<string> {
    return call("Box.CurrentSystemProxy");
  },
  /** DeleteProfile moves a profile to the Trash. */
  deleteProfile(name: string): Promise<void> {
    return call("Box.DeleteProfile", name);
  },
  /** ExportLogs asks where to save the log, and saves it there. */
  exportLogs(level: string, query: string): Promise<string> {
    return call("Box.ExportLogs", level, query);
  },
  /**
   * FormatProfile returns a configuration as sing-box reads it, indented.
   * Comments are not kept.
   */
  formatProfile(content: string): Promise<string> {
    return call("Box.FormatProfile", content);
  },
  /** Groups returns the outbound groups of the running core. */
  groups(): Promise<OutboundGroup[]> {
    return call("Box.Groups");
  },
  /** ImportFiles copies configuration files in, as dropped on the window. */
  importFiles(paths: string[]): Promise<ImportResult> {
    return call("Box.ImportFiles", paths);
  },
  /** ImportProfiles asks for configuration files and copies them in. */
  importProfiles(): Promise<ImportResult> {
    return call("Box.ImportProfiles");
  },
  /**
   * LoginItem reports whether the app opens at login. Opening the app
   * never starts sing-box.
   */
  loginItem(): Promise<boolean> {
    return call("Box.LoginItem");
  },
  /**
   * Logs returns the last lines of the log, at most limit, at or above a
   * level ("error", "warn", "info", "debug" or "all") that contain query.
   */
  logs(level: string, query: string, limit: number): Promise<LogLine[]> {
    return call("Box.Logs", level, query, limit);
  },
  /** NewProfile creates a profile from the sample and returns its name. */
  newProfile(): Promise<string> {
    return call("Box.NewProfile");
  },
  /** OpenDataDir opens the data directory in Finder. */
  openDataDir(): Promise<void> {
    return call("Box.OpenDataDir");
  },
  /** Profiles lists the configuration files. */
  profiles(): Promise<Profiles> {
    return call("Box.Profiles");
  },
  /** ReadProfile returns the text of a profile. */
  readProfile(name: string): Promise<string> {
    return call("Box.ReadProfile", name);
  },
  /**
   * Reload runs the active profile anew: the profile saved, switched or
   * updated takes effect. The node chosen and the mode come back from the
   * cache file, as sing-box keeps them.
   */
  reload(): Promise<void> {
    return call("Box.Reload");
  },
  /** RenameProfile renames a profile. */
  renameProfile(from: string, to: string): Promise<void> {
    return call("Box.RenameProfile", from, to);
  },
  /** ResetFakeIP forgets the fake IP addresses given out. */
  resetFakeIP(): Promise<void> {
    return call("Box.ResetFakeIP");
  },
  /** RevealProfile shows a profile in Finder. */
  revealProfile(name: string): Promise<void> {
    return call("Box.RevealProfile", name);
  },
  /** Rules returns the router's rules of the running core. */
  rules(): Promise<RuleInfo[]> {
    return call("Box.Rules");
  },
  /** SaveProfile writes the text of a profile. */
  saveProfile(name: string, content: string): Promise<void> {
    return call("Box.SaveProfile", name, content);
  },
  /** Select chooses an outbound of a selector. */
  select(group: string, tag: string): Promise<void> {
    return call("Box.Select", group, tag);
  },
  /** SetActive chooses the profile Start runs. */
  setActive(name: string): Promise<void> {
    return call("Box.SetActive", name);
  },
  /** SetLoginItem opens the app at login, or not. */
  setLoginItem(open: boolean): Promise<void> {
    return call("Box.SetLoginItem", open);
  },
  /**
   * SetMode switches the Clash mode: Rule, Global, Direct, or a mode the
   * configuration's rules name.
   */
  setMode(mode: string): Promise<void> {
    return call("Box.SetMode", mode);
  },
  /**
   * SetRemote changes where a subscription comes from and how often it
   * updates.
   */
  setRemote(name: string, r: Remote): Promise<void> {
    return call("Box.SetRemote", name, r);
  },
  /**
   * SetSystemProxy turns the system proxy setting on or off, and applies it
   * at once while sing-box runs.
   */
  setSystemProxy(on: boolean): Promise<void> {
    return call("Box.SetSystemProxy", on);
  },
  /** SetTheme changes the appearance. */
  setTheme(theme: Theme): Promise<void> {
    return call("Box.SetTheme", theme);
  },
  /**
   * Start runs the active profile. Nothing else starts the core: the page
   * calls it only from what the user does.
   */
  start(): Promise<void> {
    return call("Box.Start");
  },
  /** State returns the state of the core. */
  state(): Promise<Snapshot> {
    return call("Box.State");
  },
  /** Stop stops the core, after putting the system proxy back. */
  stop(): Promise<void> {
    return call("Box.Stop");
  },
  /**
   * Takeover lists what the active profile would change in the system's
   * network once started: the page asks before starting it.
   */
  takeover(): Promise<string[]> {
    return call("Box.Takeover");
  },
  /** TestOutbound measures the delay of one outbound through the core. */
  testOutbound(tag: string): Promise<number> {
    return call("Box.TestOutbound", tag);
  },
  /** Theme returns the appearance chosen. */
  theme(): Promise<Theme> {
    return call("Box.Theme");
  },
  /**
   * URLTest measures the delays of a group's outbounds through the core,
   * and returns once done.
   */
  urlTest(group: string): Promise<void> {
    return call("Box.URLTest", group);
  },
  /**
   * UpdateProfile downloads a subscription anew. A configuration that does
   * not check out is not kept. The profile running reloads.
   */
  updateProfile(name: string): Promise<void> {
    return call("Box.UpdateProfile", name);
  },
} as const;

// ---- Events ----

/** Events sent by the Go side. Subscribe with `events.name.on(listener)`. */
export const events = {
  /** StateChanged carries the state of the core to the page. */
  state: event<Snapshot>("state"),
  /** LogsChanged says the log, or the core's activity, has new lines. */
  logs: event<number>("logs"),
  /**
   * ProfilesChanged says the profiles changed outside the page, as by an
   * update of a subscription.
   */
  profiles: event<number>("profiles"),
  /**
   * Navigate sends a command of the menu to the page: a page to show, or
   * "import".
   */
  navigate: event<string>("navigate"),
} as const;
